# Generated by Django 3.2.13 on 2022-05-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detection',
            field=models.CharField(default='Not Detected', max_length=20),
        ),
    ]
