# Generated by Django 3.2.13 on 2022-05-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_core', '0002_task_detection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskID',
            field=models.IntegerField(unique=True),
        ),
    ]
